# Generated by Django 5.1.1 on 2025-02-24 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libeller', models.CharField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingenieur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('nombre_experience', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingenieurs', to='management.categorie')),
            ],
        ),
    ]
