# Generated by Django 5.1.1 on 2025-03-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('motdepasse', models.TextField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Se_connecter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingenieur',
            name='nombre_experience',
        ),
        migrations.AddField(
            model_name='ingenieur',
            name='niveaux_experience',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
