# Generated by Django 5.1.1 on 2025-03-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_connexion_se_connecter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('mot_de_passe', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Connexion',
        ),
        migrations.DeleteModel(
            name='Se_connecter',
        ),
    ]
